In [1]:
import numpy as np


In [45]:
a = np.array([[1,2]])
b = np.array([[9,2],[7,4],[5,6],[7,8]])
aug_a = np.ones((4,3))
aug_a[:,0:2] = a
print(aug_a)

[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]


In [47]:
y = np.array([[10]])
a_1 = a[:,0]
a_2 = a[:,1]
phi_1 = a_1**2
phi_2 = a_2**2
phi_3 = a_1*a_2
phi_4 = np.ones_like(phi_1)
phi_mat = np.concatenate((phi_1[:,np.newaxis],phi_2[:,np.newaxis],phi_3[:,np.newaxis],phi_4[:,np.newaxis]),axis=1)
print(phi_mat.shape)
alpha = np.linalg.pinv(phi_mat.T @ phi_mat) @ phi_mat.T @ y
G = np.zeros((2,2))
G[0,0] = alpha[0,0]*2
G[1,1] = alpha[1,0]*2
G[0,1] = alpha[2,0]
G[1,0] = alpha[2,0]

(1, 4)


In [48]:
print(alpha)

[[0.45454545]
 [1.81818182]
 [0.90909091]
 [0.45454545]]


In [49]:
G

array([[0.90909091, 0.90909091],
       [0.90909091, 3.63636364]])

In [50]:
print(phi_mat@alpha)

[[10.]]


In [53]:
kron_a = (a[:,:,None]*a[:,None,:]).reshape(1, 4)
aug_kron_a = np.ones((1,5))
aug_kron_a[:,0:4] = kron_a
# aug_kron_a[:,4] = 1/4
G_b_vec= (np.linalg.pinv(aug_kron_a.T @ aug_kron_a) @ aug_kron_a.T @ y)
G_ref = G_b_vec[0:4,0].reshape(2,2)*2
print(G_ref)
# print(kron_a)
print(aug_kron_a)

[[0.76923077 1.53846154]
 [1.53846154 3.07692308]]
[[1. 2. 2. 4. 1.]]


In [54]:
print(aug_kron_a@G_b_vec)

[[10.]]


In [55]:
G_b_vec

array([[0.38461538],
       [0.76923077],
       [0.76923077],
       [1.53846154],
       [0.38461538]])

In [56]:
0.5*(a @ G_ref * a).sum(axis=1)

array([9.61538462])

In [57]:
0.5*(a @ G * a).sum(axis=1)

array([9.54545455])

In [58]:
y - 0.5*(a @ G * a).sum(axis=1).reshape(-1,1)

array([[0.45454545]])

In [59]:
y - 0.5*(a @ G_ref * a).sum(axis=1).reshape(-1,1)

array([[0.38461538]])

In [ ]:
a = np.array([[1,2]])
y = np.array([[10]])
a_1 = a[:,0]
a_2 = a[:,1]
phi_1 = a_1**2
phi_2 = a_2**2
phi_3 = a_1*a_2
phi_4 = np.ones_like(phi_1)
phi_mat = np.concatenate((phi_1[:,np.newaxis],phi_2[:,np.newaxis],phi_3[:,np.newaxis],phi_4[:,np.newaxis]),axis=1)
alpha = np.linalg.pinv(phi_mat.T @ phi_mat) @ phi_mat.T @ y
G = np.zeros((2,2))
G[0,0] = alpha[0,0]*2
G[1,1] = alpha[1,0]*2
G[0,1] = alpha[2,0]
G[1,0] = alpha[2,0]
kron_a = (a[:,:,None]*a[:,None,:]).reshape(1, 4)
aug_kron_a = np.ones((1,5))
aug_kron_a[:,0:4] = kron_a
G_b_vec= (np.linalg.pinv(aug_kron_a.T @ aug_kron_a) @ aug_kron_a.T @ y)
G_ref = G_b_vec[0:4,0].reshape(2,2)*2

In [8]:
import numpy as np

# Data
a = np.array([[1, 2]])
y = np.array([[10]])

# Basis function approach
a_1 = a[:, 0]
a_2 = a[:, 1]
phi_1 = a_1**2
phi_2 = a_2**2
phi_3 = a_1 * a_2
phi_4 = a_1 * a_2
phi_5 = np.ones_like(phi_1)
phi_mat = np.concatenate((phi_1[:, np.newaxis], phi_2[:, np.newaxis], phi_3[:, np.newaxis], phi_4[:, np.newaxis], phi_5[:, np.newaxis]), axis=1)

# Compute alpha
alpha = np.linalg.pinv(phi_mat.T @ phi_mat) @ phi_mat.T @ y

# Construct G
G = np.zeros((2, 2))
G[0, 0] = alpha[0, 0] *2
G[1, 1] = alpha[1, 0] *2
G[0, 1] = alpha[2, 0] *2
G[1, 0] = alpha[3, 0] *2

print("G from basis functions:")
print(G)

# Least squares approach
kron_a = (a[:, :, None] * a[:, None, :]).reshape(1, 4)
aug_kron_a = np.ones((1, 5))
aug_kron_a[:, 0:4] = kron_a

# Compute G_b vector
G_b_vec = np.linalg.pinv(aug_kron_a.T @ aug_kron_a) @ aug_kron_a.T @ y

# Extract G from G_b_vec
G_ref = G_b_vec[0:4, 0].reshape(2, 2) *2

print("G_ref from least squares:")
print(G_ref)

# Check if G is equal to G_ref
print("Are G and G_ref equal?")
print(np.allclose(G, G_ref))

G from basis functions:
[[0.76923077 1.53846154]
 [1.53846154 3.07692308]]
G_ref from least squares:
[[0.76923077 1.53846154]
 [1.53846154 3.07692308]]
Are G and G_ref equal?
True
